export const ActionTypes = {
    FETCH_ALL:"FETCH_ALL",
    CREATE_POST:"CREATE_POST",
    UPDATE_POST:"UPDATE_POST",
    UPDATE_POST_FINISH:"UPDATE_POST_FINISH",
    DELETE_POST:"DELETE_POST",
    LIKE_POST:"LIKE_POST"
}